export const ModelConfig = [
  {
    label: '简体中文',
    key: 'ch_mobile',
    det: 'det/ch_PP-OCRv4_det_mobile.onnx',
    rec: 'rec/ch_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/ch_PP-OCRv4_rec_mobile/ppocr_keys_v1.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '简体中文(服务器)',
    key: 'ch_server',
    det: 'det/ch_PP-OCRv4_det_server.onnx',
    rec: 'rec/ch_PP-OCRv4_rec_server.onnx',
    dict: 'rec/ch_PP-OCRv4_rec_server/ppocr_keys_v1.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '繁體中文',
    key: 'chinese_cht',
    det: 'det/ch_PP-OCRv4_det_server.onnx',
    rec: 'rec/chinese_cht_PP-OCRv3_rec_mobile.onnx',
    dict: 'rec/chinese_cht_PP-OCRv3_rec_mobile/chinese_cht_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '英文',
    key: 'en_mobile',
    det: 'det/en_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/en_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/en_PP-OCRv4_rec_mobile/en_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '阿拉伯文',
    key: 'ar_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/arabic_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/arabic_PP-OCRv4_rec_mobile/arabic_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '塞尔维亚文',
    key: 'cyrillic_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/cyrillic_PP-OCRv3_rec_mobile.onnx',
    dict: 'rec/cyrillic_PP-OCRv3_rec_mobile/cyrillic_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '梵文',
    key: 'devanagari_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/devanagari_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/devanagari_PP-OCRv4_rec_mobile/devanagari_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '日文',
    key: 'japan_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/japan_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/japan_PP-OCRv4_rec_mobile/japan_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '卡纳达语',
    key: 'ka_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/ka_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/ka_PP-OCRv4_rec_mobile/ka_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '韩文',
    key: 'korean_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/korean_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/korean_PP-OCRv4_rec_mobile/korean_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '拉丁文',
    key: 'latin_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/latin_PP-OCRv3_rec_mobile.onnx',
    dict: 'rec/latin_PP-OCRv3_rec_mobile/latin_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '泰米尔文',
    key: 'ta_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/ta_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/ta_PP-OCRv4_rec_mobile/ta_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
  {
    label: '泰卢固文',
    key: 'te_mobile',
    det: 'det/multi_PP-OCRv3_det_mobile.onnx',
    rec: 'rec/te_PP-OCRv4_rec_mobile.onnx',
    dict: 'rec/te_PP-OCRv4_rec_mobile/te_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_mobile.onnx',
  },
];
