export const ModelConfig = [
  {
    label: '简体中文',
    key: 'ch_mobile',
    det: 'det/ch_PP-OCRv4_det_infer.onnx',
    rec: 'rec/ch_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/ch_PP-OCRv4_rec_infer/ppocr_keys_v1.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '简体中文(服务器)',
    key: 'ch_server',
    det: 'det/ch_PP-OCRv4_det_server_infer.onnx',
    rec: 'rec/ch_PP-OCRv4_rec_server_infer.onnx',
    dict: 'rec/ch_PP-OCRv4_rec_server_infer/ppocr_keys_v1.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '繁體中文',
    key: 'chinese_cht',
    det: 'det/ch_PP-OCRv4_det_infer.onnx',
    rec: 'rec/chinese_cht_PP-OCRv3_rec_infer.onnx',
    dict: 'rec/chinese_cht_PP-OCRv3_rec_infer/chinese_cht_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '英文',
    key: 'en_mobile',
    det: 'det/en_PP-OCRv3_det_infer.onnx',
    rec: 'rec/en_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/en_PP-OCRv4_rec_infer/en_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '阿拉伯文',
    key: 'ar_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/arabic_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/arabic_PP-OCRv4_rec_infer/arabic_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '塞尔维亚文',
    key: 'cyrillic_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/cyrillic_PP-OCRv3_rec_infer.onnx',
    dict: 'rec/cyrillic_PP-OCRv3_rec_infer/cyrillic_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '梵文',
    key: 'devanagari_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/devanagari_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/devanagari_PP-OCRv4_rec_infer/devanagari_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '日文',
    key: 'japan_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/japan_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/japan_PP-OCRv4_rec_infer/japan_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '卡纳达语',
    key: 'ka_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/ka_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/ka_PP-OCRv4_rec_infer/ka_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '韩文',
    key: 'korean_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/korean_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/korean_PP-OCRv4_rec_infer/korean_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '拉丁文',
    key: 'latin_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/latin_PP-OCRv3_rec_infer.onnx',
    dict: 'rec/latin_PP-OCRv3_rec_infer/latin_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '泰米尔文',
    key: 'ta_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/ta_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/ta_PP-OCRv4_rec_infer/ta_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
  {
    label: '泰卢固文',
    key: 'te_mobile',
    det: 'det/Multilingual_PP-OCRv3_det_infer.onnx',
    rec: 'rec/te_PP-OCRv4_rec_infer.onnx',
    dict: 'rec/te_PP-OCRv4_rec_infer/te_dict.txt',
    cls: 'cls/ch_ppocr_mobile_v2.0_cls_infer.onnx',
  },
];
