allowBuilds:
  core-js: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@cyia/dl@1.5.5'
  - '@cyia/external-call@1.5.5'
  - '@cyia/util@1.5.5'
  - '@cyia/vfs2@1.5.5'
  - '@cyia/zip@1.5.5'
